name: Testing-infra

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: spy
    steps:
    - name: this is first job
      run: echo "This is github action"
      
    - name: Checkout  
      uses: actions/checkout@v5.0.0

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: eea770a2-17d2-4067-8827-0ebedcf85029
        tenant-id: a6395b74-f5d3-427b-b4c0-5a918ab2e374
        subscription-id: 388a2121-d962-4059-8c36-c24d806cad40

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: environment/stage
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      working-directory: environment/stage
      run: terraform init -input=false
    
    - name: Terraform Validate
      id: validate
      working-directory: environment/stage
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      working-directory: environment/stage
      continue-on-error: true
      
  terraform-apply:
    runs-on: spy
    #environment: stage
    needs: terraform-init-plan
    steps:
    - name: Checkout  
      uses: actions/checkout@v5.0.0

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: eea770a2-17d2-4067-8827-0ebedcf85029
        tenant-id: a6395b74-f5d3-427b-b4c0-5a918ab2e374
        subscription-id: 388a2121-d962-4059-8c36-c24d806cad40

    - name: Terraform Init
      id: init
      working-directory: environment/stage
      run: terraform init -input=false    

    - name: Terraform Apply
      id: apply
      working-directory: environment/stage
      run: terraform apply --auto-approve
      continue-on-error: true    
