name: Testing-infra

on: workflow_dispatch

jobs:
  terraform-infra:
    runs-on: spy
    steps:
    - name: this is first job
      run: echo "This is github action"
      
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color   
      
